In [2]:
import pandas as pd

from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [3]:
train = pd.read_csv('./EGR_Cooler_data/train_data.csv')
test = pd.read_csv('./EGR_Cooler_data/test_data.csv')

In [4]:
X_train = train.drop(['op10_test', 'op10_time_series', 'op20_test', 'op20_time_series',
                            'op30_test', 'op30_time_series', 'op40_test', 'op40_time_series', 
                            'op50_test', 'op50_time_series', 'op60_test', 
                            'op40_length', 'op40_width', 'op40_height', 
                            'op40_light_sensor', 'op40_temperature', 'op40_scratch', 'op40_operator', 
                            'op50_length', 'op50_width', 'op50_height',
                            'op50_light_sensor', 'op50_temperature', 'op50_scratch', 'op50_operator',
                            'op60_length', 'op60_width', 'op60_height', 
                            'op60_light_sensor', 'op60_scratch', 'uniform_distribution'], axis = 1)
X_train.head()

,body_length,body_width,body_height,wavyfin_length,wavyfin_width,wavyfin_height,pipe1_length,pipe1_width,pipe1_height,pipe2_length,...,op20_light_sensor,op20_scratch,op20_operator,op30_length,op30_width,op30_height,op30_electricity_sensor,op30_light_sensor,op30_scratch,op30_operator
0,199.996,100.002,50.001,100.000,49.997,59.997,30.000,50.003,29.996,30.000,...,0,1,1,199.995873,180.106820,59.996905,94.711471,0,1,1
1,200.002,100.000,49.998,99.999,50.002,60.000,29.999,49.994,29.999,30.007,...,0,1,1,200.001735,179.993792,59.999933,94.880748,0,1,1
2,199.998,100.000,49.998,100.003,50.003,59.998,29.995,50.002,30.000,30.003,...,0,1,1,199.997595,180.007309,59.997682,92.783317,0,1,1
3,200.002,100.000,50.000,100.000,50.003,60.000,30.001,49.995,29.998,30.002,...,0,1,1,200.001981,179.995833,60.000453,93.951689,0,1,1
4,200.001,100.001,49.999,100.003,49.997,59.996,30.000,50.001,29.996,30.002,...,0,1,1,200.001256,180.005777,59.995941,90.609768,0,1,1

In [5]:
Y_train = train['op60_test']
Y_train.head()

0    1
1    0
2    0
3    0
4    0
Name: op60_test, dtype: int64

In [6]:
X_test = test.drop(['op10_test', 'op10_time_series', 'op20_test', 'op20_time_series',
                            'op30_test', 'op30_time_series', 'op40_test', 'op40_time_series', 
                            'op50_test', 'op50_time_series', 'op60_test', 
                            'op40_length', 'op40_width', 'op40_height', 
                            'op40_light_sensor', 'op40_temperature', 'op40_scratch', 'op40_operator', 
                            'op50_length', 'op50_width', 'op50_height',
                            'op50_light_sensor', 'op50_temperature', 'op50_scratch', 'op50_operator',
                            'op60_length', 'op60_width', 'op60_height', 
                            'op60_light_sensor', 'op60_scratch', 'uniform_distribution'], axis = 1)
X_test.head()

,body_length,body_width,body_height,wavyfin_length,wavyfin_width,wavyfin_height,pipe1_length,pipe1_width,pipe1_height,pipe2_length,...,op20_light_sensor,op20_scratch,op20_operator,op30_length,op30_width,op30_height,op30_electricity_sensor,op30_light_sensor,op30_scratch,op30_operator
0,199.997,99.999,50.003,100.000,50.005,60.003,29.996,50.004,30.002,29.998,...,0,1,3,199.997061,180.005558,60.002786,95.000563,0,1,3
1,199.999,100.001,50.002,99.996,50.000,60.004,29.998,50.004,29.995,30.000,...,0,1,3,199.999360,180.005180,60.003705,91.815773,0,1,3
2,199.999,100.001,50.002,100.001,50.001,60.003,29.997,50.001,30.003,30.001,...,0,1,3,199.999315,180.004519,60.002609,94.368763,0,1,3
3,200.002,99.996,49.999,100.001,49.998,60.000,30.000,50.006,30.001,30.001,...,0,1,3,200.002048,180.001510,59.999508,96.679591,0,1,3
4,199.999,100.003,50.003,100.000,50.001,60.000,30.000,49.998,30.002,30.001,...,0,1,3,199.999422,180.001309,59.999977,94.037526,0,1,3

In [7]:
Y_test = test['op60_test']
Y_test.head()

0    0
1    0
2    0
3    0
4    0
Name: op60_test, dtype: int64

In [9]:
lr_clf = LogisticRegression()
knn_clf = KNeighborsClassifier(n_neighbors=8)
vo_clf = VotingClassifier( estimators=[('LR',lr_clf),('KNN',knn_clf)] , voting='soft' )

vo_clf.fit(X_train , Y_train)
pred = vo_clf.predict(X_test)
print('Voting 분류기 정확도: {0:.4f}'.format(accuracy_score(Y_test , pred)))

classifiers = [lr_clf, knn_clf]
for classifier in classifiers:
    classifier.fit(X_train , Y_train)
    pred = classifier.predict(X_test)
    class_name= classifier.__class__.__name__
    print('{0} 정확도: {1:.4f}'.format(class_name, accuracy_score(Y_test , pred)))

C:\Users\clubc\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

Voting 분류기 정확도: 0.9405
LogisticRegression 정확도: 0.9405

C:\Users\clubc\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

KNeighborsClassifier 정확도: 0.9405